#pragma once

#include <stddef.h>
#include <stdint.h>

// able entry
// generated by the Julia pass in qtable.c
// runtime lib references these as extern

typedef struct {
  const char* key;   // e.g. "add_7_11"
  const char* qasm;  // embedded qasm bytes
  size_t qasm_len;   // length of qasm bytes
} quantum_entry_t;

extern quantum_entry_t quantum_table[];
extern int quantum_table_size;

// runtime api
// called from mutated IR:
//   call i32 @quantum_execute(i8* "add_7_11", i8* "add")

int32_t quantum_execute(const char* key, const char* decoder);
